services:
  cockroachdb:
    image: cockroachdb/cockroach:v24.1.20
    container_name: cockroachdb
    command: start-single-node --insecure
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - cockroach-data-emul8-dev:/cockroach/cockroach-data
    restart: unless-stopped

volumes:
  cockroach-data-emul8-dev: