packages:
  - src/apps/*
  - src/services/*
  - src/packages/*
  - src/tooling/*

nodeVersion: 24.3.0

catalog:
  typescript: 5.8.3
  tsx: 4.20.3
  prettier: 3.6.2
  "@types/node": 24.0.12
  eslint: 9.30.1
  "@trpc/server": 11.4.3
  "@trpc/client": 11.4.3
  "@trpc/react-query": 11.4.3
  zod: 3.25.76
